---
resources:
- name: resource-tutorial # test push
  type: git
  source:
    uri: https://github.com/markharrison17/TestRepo.git
- name: resource-gist
  type: git
  source:
    branch: master
    uri: {{gist-url}}
    private_key: {{github-private-key}}

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
      trigger: true
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}

- name: job-show-date
  plan:
  - get: resource-tutorial
  - get: resource-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: resource-gist
      run:
        path: cat
        args: [resource-gist/bumpme]
